# Generated by Django 3.2.15 on 2022-08-26 11:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона')),
                ('mobile_operator_code', models.CharField(max_length=10, verbose_name='Код мобильного оператора')),
                ('tag', models.SlugField(verbose_name='Тег')),
                ('client_timezone', models.CharField(max_length=20, verbose_name='Часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(db_index=True, verbose_name='Зарегистрирован')),
                ('message', models.TextField(verbose_name='Сообщение клиенту')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='Дата и время окончания рассылки')),
                ('time_start', models.TimeField(verbose_name='Время начала рассылки')),
                ('time_end', models.TimeField(verbose_name='Время окончания рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(db_index=True, verbose_name='Зарегистрирован')),
                ('deliver_time', models.DateTimeField(db_index=True, verbose_name='Время отравки сообщения')),
                ('status', models.CharField(choices=[('REG', 'Зерегистрировано'), ('PO', 'Ожидает отправки'), ('DE', 'Отправлено')], default='REG', max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.mailinglist', verbose_name='Рассылки')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='mailing.mailinglist', verbose_name='Рассылки'),
        ),
    ]
