# Generated by Django 3.2.15 on 2022-08-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RenameField(
            model_name='mailinglist',
            old_name='end_time',
            new_name='closed_at',
        ),
        migrations.RenameField(
            model_name='mailinglist',
            old_name='time_end',
            new_name='sending_time_end',
        ),
        migrations.RenameField(
            model_name='mailinglist',
            old_name='time_start',
            new_name='sending_time_start',
        ),
    ]
