# Generated by Django 4.0.7 on 2022-08-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20220829_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client',
        ),
    ]
