# Generated by Django 4.0.7 on 2022-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_message_deliver_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='deliver_time',
            field=models.TimeField(db_index=True, null=True, verbose_name='Время отравки сообщения'),
        ),
    ]
